export default [
  {
    teamId: 1,
    name: 'Siegmund Neumayer',
    image: '/assets/players/human-thrower.jpg',
    position: 'Thrower',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [
      'Sure Hands',
      'Throw',
    ],
  },
  {
    teamId: 1,
    name: 'Norman Wahler',
    image: '/assets/players/human-catcher.png',
    position: 'Catcher',
    agility: 3,
    strength: 2,
    movement: 8,
    armor: 7,
    skills: [
      'Catch',
      'Dodge',
    ],
  },
  {
    teamId: 1,
    name: 'Meinolf Klügmann',
    image: '/assets/players/human-catcher.png',
    position: 'Catcher',
    agility: 3,
    strength: 2,
    movement: 8,
    armor: 7,
    skills: [
      'Catch',
      'Dodge',
    ],
  },
  {
    teamId: 1,
    name: 'Hildebrand Buxbaum',
    image: '/assets/players/human-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 7,
    armor: 8,
    skills: [
      'Block'
    ],
  },
  {
    teamId: 1,
    name: 'Liebhard Drachmann',
    image: '/assets/players/human-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 7,
    armor: 8,
    skills: [
      'Block'
    ],
  },
  {
    teamId: 1,
    name: 'Wigmar Cullmann',
    image: '/assets/players/human-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 7,
    armor: 8,
    skills: [
      'Block'
    ],
  },
  {
    teamId: 1,
    name: 'Ernest Scheibel',
    image: '/assets/players/human-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 7,
    armor: 8,
    skills: [
      'Block'
    ],
  },
  {
    teamId: 1,
    name: 'Grimwald Goldfarb',
    image: '/assets/players/human-lineman.jpg',
    position: 'Lineman',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [],
  },
  {
    teamId: 1,
    name: 'Bert Reimold',
    image: '/assets/players/human-lineman.jpg',
    position: 'Lineman',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [],
  },
  {
    teamId: 1,
    name: 'Arnulf Lasch',
    image: '/assets/players/human-lineman.jpg',
    position: 'Lineman',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [],
  },
  {
    teamId: 1,
    name: 'Witold Schmidt',
    image: '/assets/players/human-lineman.jpg',
    position: 'Lineman',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Trezas Hollowfist',
    image: '/assets/players/orc-thrower.jpg',
    position: 'Thrower',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 8,
    skills: [
      'Sure Hands',
      'Throw',
    ],
  },
  {
    teamId: 2,
    name: 'Gol Brightshift',
    image: '/assets/players/orc-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 9,
    skills: [
      'Block',
    ],
  },
  {
    teamId: 2,
    name: 'Grul Vicefang',
    image: '/assets/players/orc-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 9,
    skills: [
      'Block',
    ],
  },
  {
    teamId: 2,
    name: 'Mus Barrenheart',
    image: '/assets/players/orc-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 9,
    skills: [
      'Block',
    ],
  },
  {
    teamId: 2,
    name: 'Thularl Stonekill',
    image: '/assets/players/orc-blitzer.jpg',
    position: 'Blitzer',
    agility: 3,
    strength: 3,
    movement: 6,
    armor: 9,
    skills: [
      'Block',
    ],
  },
  {
    teamId: 2,
    name: 'Trusuk Sourbreath',
    image: '/assets/players/black-orc.jpg',
    position: 'Black Orc',
    agility: 2,
    strength: 4,
    movement: 4,
    armor: 9,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Kurangaz Stonelock',
    image: '/assets/players/black-orc.jpg',
    position: 'Black Orc',
    agility: 2,
    strength: 4,
    movement: 4,
    armor: 9,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Brast Tuskteeth',
    image: '/assets/players/black-orc.jpg',
    position: 'Black Orc',
    agility: 2,
    strength: 4,
    movement: 4,
    armor: 9,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Hath Halffist',
    image: '/assets/players/black-orc.jpg',
    position: 'Black Orc',
    agility: 2,
    strength: 4,
    movement: 4,
    armor: 9,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Brulerl Quickmaul',
    image: '/assets/players/lineorc.jpg',
    position: 'Lineorc',
    agility: 3,
    strength: 3,
    movement: 5,
    armor: 9,
    skills: [],
  },
  {
    teamId: 2,
    name: 'Zolgorg Stormheart',
    image: '/assets/players/lineorc.jpg',
    position: 'Lineorc',
    agility: 3,
    strength: 3,
    movement: 5,
    armor: 9,
    skills: [],
  },
];
